(use-package add-node-modules-path :ensure t)
(use-package color-theme-solarized :ensure t)
(use-package csv-mode :ensure t)
(use-package dash :ensure t)
(use-package diminish
  :ensure t
  :config
  (diminish 'eldoc-mode)
  )
(use-package dockerfile-mode :ensure t)
(use-package exec-path-from-shell :ensure t)
(use-package gitconfig-mode :ensure t)
(use-package gitignore-mode :ensure t)
(use-package helm-bundle-show :ensure t)
(use-package helm-elscreen :ensure t)
(use-package hgrc-mode :ensure t)
(use-package hgignore-mode :ensure t)
(use-package json-mode :ensure t)
(use-package kotlin-mode :ensure t)
(use-package less-css-mode :ensure t)
(use-package magit-popup :ensure t)
(use-package popup :ensure t)
(use-package rhtml-mode :ensure t)
(use-package rspec-mode :ensure t)
(use-package ruby-end :ensure t)
(use-package s :ensure t)
(use-package slim-mode :ensure t)
(use-package wgrep :ensure t)
(use-package wgrep-helm :ensure t)
(use-package yagist :ensure t)
(use-package yaml-mode :ensure t)
(use-package yasnippet :ensure t)
